apiVersion: v1
kind: Secret
metadata:
  name: api-env
type: Opaque
stringData:
  # Environment settings
  NODE_ENV: "development"
  APP_PORT: "3000"
  APP_NAME: "NestJS API"
  API_PREFIX: "api"
  APP_FALLBACK_LANGUAGE: "en"
  APP_HEADER_LANGUAGE: "x-custom-lang"
  FRONTEND_DOMAIN: "http://localhost:3000"
  BACKEND_DOMAIN: "http://localhost:3000"
  
  # Database connection - Updated for Kubernetes
  DATABASE_TYPE: "postgres"
  DATABASE_HOST: "postgres"  # This matches your Kubernetes PostgreSQL service name
  DATABASE_PORT: "5432"
  DATABASE_USERNAME: "postgresadmin"
  DATABASE_PASSWORD: "admin123"
  DATABASE_NAME: "postgresdb"
  DATABASE_SYNCHRONIZE: "true"
  DATABASE_MAX_CONNECTIONS: "100"
  DATABASE_SSL_ENABLED: "false"
  DATABASE_REJECT_UNAUTHORIZED: "false"
  
  # Redis configuration
  REDIS_HOST: "redis"  # If you deploy Redis, use its service name
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  
  # JWT Configuration
  JWT_ACCESS_SECRET: "your_access_secret_key"
  JWT_REFRESH_SECRET: "your_refresh_secret_key"
  JWT_ACCESS_EXPIRATION_TIME: "3600"
  JWT_REFRESH_EXPIRATION_TIME: "604800"
  
  # AWS Configuration
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: ""
  AWS_S3_BUCKET: ""
  